// templates.ts

export const templates = [
  {
    id: 1,
    title: "MODERN MINIMALIST",
    subtitle: "Seni dalam kesederhanaan dan ruang kosong.",
    author: "DESIGN STUDIO",
    synopsis: "Buku ini mengeksplorasi bagaimana elemen minimalis dapat menciptakan dampak visual yang kuat dalam desain modern melalui penggunaan ruang dan tipografi yang tepat.",
    category: "Non-Fiksi",
    bgImage: "https://images.unsplash.com/photo-1550684848-fac1c5b4e853?q=80&w=800",
    titleColor: "text-white",
    authorColor: "text-slate-300",
  },
  {
    id: 2,
    title: "GALAXY VOYAGER",
    subtitle: "Menjelajahi batas akhir alam semesta.",
    author: "CAPTAIN COSMOS",
    synopsis: "Perjalanan melintasi lubang cacing menuju galaksi yang belum pernah terjamah oleh manusia sebelumnya untuk menemukan rumah baru bagi umat manusia.",
    category: "Sci-Fi",
    bgImage: "https://images.unsplash.com/photo-1451187580459-43490279c0fa?q=80&w=800",
    titleColor: "text-cyan-400",
    authorColor: "text-white",
  },
  {
    id: 3,
    title: "JEJAK KABUT",
    subtitle: "Kisah tentang mereka yang hilang dan tak pernah kembali.",
    author: "WRITER NAME",
    synopsis: "Kabut di desa itu tidak pernah benar-benar hilang. Begitu juga dengan ingatan tentang mereka yang melangkah masuk ke dalamnya dan lenyap selamanya.",
    category: "Misteri",
    bgImage: "https://images.unsplash.com/photo-1503756234508-e32369269deb?q=80&w=800",
    titleColor: "text-white",
    authorColor: "text-white",
  },
  {
    id: 4,
    title: "HUTAN TERLARANG",
    subtitle: "Jangan pernah melangkah keluar dari jalur setapak.",
    author: "SILVIA ROSE",
    synopsis: "Legenda mengatakan hutan ini bernapas. Siapa pun yang masuk tanpa izin akan menjadi bagian dari pepohonan selamanya.",
    category: "Horor",
    bgImage: "https://images.unsplash.com/photo-1441974231531-c6227db76b6e?q=80&w=800",
    titleColor: "text-emerald-400",
    authorColor: "text-slate-200",
  },
  {
    id: 5,
    title: "CINTA DI VERONA",
    subtitle: "Takdir yang tertulis di antara bintang-bintang.",
    author: "ROMEO DE CAPRIO",
    synopsis: "Dua hati yang terpisah oleh perseteruan keluarga lama, mencoba bersatu kembali di kota yang penuh dengan sejarah dan air mata.",
    category: "Romantis",
    bgImage: "https://images.unsplash.com/photo-1518131148944-4467ec923c69?q=80&w=800",
    titleColor: "text-rose-500",
    authorColor: "text-rose-200",
  },
  {
    id: 6,
    title: "KODE MASA DEPAN",
    subtitle: "Membangun dunia baru dengan kecerdasan buatan.",
    author: "ALAN TURING JR.",
    synopsis: "Panduan komprehensif bagi para pengembang untuk memahami etika dan teknis di balik algoritma yang menggerakkan dunia modern.",
    category: "Non-Fiksi",
    bgImage: "https://images.unsplash.com/photo-1518770660439-4636190af475?q=80&w=800",
    titleColor: "text-indigo-400",
    authorColor: "text-indigo-100",
  },
  {
    id: 7,
    title: "DETEKTIF KOTA",
    subtitle: "Setiap sudut jalan menyimpan rahasia gelap.",
    author: "ARTHUR CONAN",
    synopsis: "Seorang detektif swasta harus berpacu dengan waktu untuk menghentikan dalang kriminal sebelum fajar menyingsing di London.",
    category: "Misteri",
    bgImage: "https://images.unsplash.com/photo-1478720568477-152d9b164e26?q=80&w=800",
    titleColor: "text-orange-500",
    authorColor: "text-orange-200",
  },
  {
    id: 8,
    title: "ARKADE KLASIK",
    subtitle: "Kembali ke masa kejayaan video game 8-bit.",
    author: "RETRO GAMER",
    synopsis: "Nostalgia murni tentang bagaimana koin-koin dan mesin arkade mengubah budaya populer selamanya di era 80-an.",
    category: "Fiksi",
    bgImage: "https://images.unsplash.com/photo-1550745165-9bc0b252726f?q=80&w=800",
    titleColor: "text-yellow-400",
    authorColor: "text-white",
  },
  {
    id: 9,
    title: "SENJA TERAKHIR",
    subtitle: "Mengenang hari-hari yang takkan pernah kembali.",
    author: "ELARA MOON",
    synopsis: "Sebuah kumpulan puisi tentang kehilangan, harapan, dan keindahan yang ditemukan dalam perpisahan yang tak terelakkan.",
    category: "Romantis",
    bgImage: "https://images.unsplash.com/photo-1494548162494-384bba4ab999?q=80&w=800",
    titleColor: "text-amber-400",
    authorColor: "text-amber-100",
  },
  {
    id: 10,
    title: "CYBERNETIC",
    subtitle: "Manusia atau mesin? Batasnya mulai memudar.",
    author: "VINCENZO X",
    synopsis: "Di tahun 2099, modifikasi tubuh adalah hal lazim. Namun, seorang pria menyadari bahwa ia kehilangan jiwanya di dalam sirkuit logam.",
    category: "Sci-Fi",
    bgImage: "https://images.unsplash.com/photo-1544197150-b99a580bb7a8?q=80&w=800",
    titleColor: "text-purple-400",
    authorColor: "text-white",
  }
];

export const categories = ["Semua","Custom", "Fiksi", "Non-Fiksi", "Sci-Fi", "Misteri", "Horor", "Romantis"];